spring.datasource.url=jdbc:postgresql://localhost:5433/smart_ata 
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=7200000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eduardofloresadm@gmail.com
spring.mail.password=esf963852
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.activation.url=http://localhost:8080/api/auth/activate

